services:
  - type: web
    name: spring-boot-angular-app
    runtime: docker
    plan: free
    buildCommand: ""   # not needed because Dockerfile handles build
    startCommand: ""   # also handled inside Dockerfile
