 server.port=8080


spring.application.name=adhivedha

spring.data.mongodb.database=adhivedha
spring.data.mongodb.port=27017
spring.data.mongodb.host=localhost


spring.servlet.multipart.max-file-size=500KB
spring.servlet.multipart.max-request-size=500KB

logging.level.com.example=DEBUG
logging.level.org.springframework.web=INFO


logging.file.name=logs/app.log
logging.level.root=INFO
logging.level.com.myapp=DEBUG